apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}-ns
spec:
  ports:
  - name: http
    nodePort: {{ .Values.service.nodeport}}
    port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.typeservice }}