name: test-gitops

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        default: "local"
        options:
          - local
      deploy_mode:
        type: choice
        description: Deployment Run mode
        required: true
        default: "dryrun"
        options:
          - dryrun
          - apply
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    - name: Run a multi-line script
      if: ${{ github.event.inputs.deploy_mode == 'dryrun' }}
      run: |
        echo Add other actions to build,
        echo test, and deploy your projec
    # name: deploy
    # runs-on: [localhost]
    # environment: ${{ github.event.inputs.env }}
    # steps:
    #   - name: Checkout Helm Repository
    #     uses: test-few
    #     with:
    #       repository: gitops/mychart
    #       ref: main
    #       token: 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
    #       path: ./mychart

    #   - name: "Dry run Build Template and Deploy"
    #     if: ${{ github.event.inputs.deploy_mode == 'dryrun' }}
    #     run: |
    #       helm template ${{github.event.inputs.env}} ./mychart/ --output-dir output/ --debug
          
    #       cat output/mychart/template/deployment.yaml
    #       cat output/mychart/template/service.yaml
    #       cat output/mychart/template/configmap.yaml
