name: test-gitops

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Environment
        required: true
        default: "local"
        options:
          - local
          - dev
          - sit
          - uat
          - prd
      deploy_mode:
        type: choice
        description: Deployment Run mode
        required: true
        default: "dryrun"
        options:
          - dryrun
          - apply
      times:
        type: choice
        description: How many times?
        required: true
        default: "Not-the-first-time"
        options:
          - Not-the-first-time
          - the-first-time
      repository:
        type: choice
        description: repository
        required: true
        default: "local"
        options:
          - local
          - https://github.com/oattoman7522/gitops.git
      server_k8s:
        type: choice
        description: server_k8s
        required: true
        default: "local"
        options:
          - local
          - https://kubernetes.default.svc
      runner_tag:
        type: choice
        description:  Github Runner
        required: true
        default: "local"
        options:
          - local
          - wsl

env:
  Directory: "/root/gitops/gitops"

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
    - self-hosted
    - ${{ github.event.inputs.runner_tag }}
    steps:
    - name: Dry run helm-templat test-gitops
      if: ${{ github.event.inputs.deploy_mode == 'dryrun' }}
      working-directory: ${{env.Directory}}
      run: |
        git fetch
        git pull
        helm template ${{github.event.inputs.env}}-app ./mychart --values mychart/values.yaml --set gitrepo=${{github.event.inputs.repository}} --set pathgitops=output/application-${{github.event.inputs.env}}/mychart/templates/ --set serverk8s=${{github.event.inputs.server_k8s}} --output-dir output/application-${{github.event.inputs.env}}/
        cat output/application-${{github.event.inputs.env}}/mychart/templates/argo-template.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/deployment.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/service.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/configmap.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/namespace.yaml

    - name: Apply helm-template test-gitops
      if: ${{ github.event.inputs.deploy_mode == 'apply' }}
      working-directory: ${{env.Directory}}
      run: |
        git fetch
        git pull
        helm template ${{github.event.inputs.env}}-app ./mychart --values mychart/values.yaml --set gitrepo=${{github.event.inputs.repository}} --set pathgitops=output/application-${{github.event.inputs.env}}/mychart/templates/ --set serverk8s=${{github.event.inputs.server_k8s}} --output-dir output/application-${{github.event.inputs.env}}/
        cat output/application-${{github.event.inputs.env}}/mychart/templates/argo-template.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/deployment.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/service.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/configmap.yaml
        cat output/application-${{github.event.inputs.env}}/mychart/templates/namespace.yaml
        mkdir -p argocd/application-${{github.event.inputs.env}}
        mv output/application-${{github.event.inputs.env}}/mychart/templates/argo-template.yaml arogcd/application-${{github.event.inputs.env}}/argo-template.yaml
        git fetch
        git add .
        git commit -m "update version env-${{github.event.inputs.env}}"
        git push origin implement

    - name: Apply deploy gitops test-gitops
      if: ${{ github.event.input.times == 'the-first-time' }}
      working-directory: ${{env.Directory}}
      run: | 
        cat arogcd/application-${{github.event.inputs.env}}/argo-template.yaml
        kubectl create -f arogcd/application-${{github.event.inputs.env}}/argo-template.yaml
        kubectl get application -n argocd




    # - name: Apply Deploy gitops
    #   if: ${{ github.event.inputs.deploy_mode == 'apply' }}
    #   run: |
    #     argocd app create ${{github.event.inputs.env}}-app --repo ${{github.event.inputs.repository}} --path output/mychart/templates/ --dest-namespace ${{github.event.inputs.env}}-ns --dest-server https://kubernetes.default.svc
    #     argocd app sync ${{github.event.inputs.env}}-app
    # name: deploy
    # runs-on: [localhost]
    # environment: ${{ github.event.inputs.env }}
    # steps:
    #   - name: Checkout Helm Repository
    #     uses: test-few
    #     with:
    #       repository: gitops/mychart
    #       ref: main
    #       token: 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
    #       path: ./mychart

    #   - name: "Dry run Build Template and Deploy"
    #     if: ${{ github.event.inputs.deploy_mode == 'dryrun' }}
    #     run: |
    #       helm template ${{github.event.inputs.env}} ./mychart/ --output-dir output/ --debug
          
    #       cat output/mychart/template/deployment.yaml
    #       cat output/mychart/template/service.yaml
    #       cat output/mychart/template/configmap.yaml
